"""init schema

Revision ID: e006d0c2abfa
Revises: 
Create Date: 2026-06-21 07:38:30.962921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e006d0c2abfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_publish_mode', sa.Enum('MANUAL_REVIEW', 'AUTO_SCHEDULE', 'FULL_AUTO', name='autopublishmode'), nullable=False),
    sa.Column('publish_rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=True)
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('cloudinary_video_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'GENERATING_CONTENT', 'READY_FOR_REVIEW', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('assemblyai_transcript_id', sa.String(length=128), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('transcript_confidence', sa.Float(), nullable=True),
    sa.Column('ai_title', sa.String(length=200), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_pinned_comment', sa.Text(), nullable=True),
    sa.Column('ai_community_post', sa.Text(), nullable=True),
    sa.Column('ai_thumbnail_text', sa.String(length=120), nullable=True),
    sa.Column('ai_thumbnail_suggestions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_generation_raw', sa.JSON(), nullable=True),
    sa.Column('final_title', sa.String(length=200), nullable=True),
    sa.Column('final_description', sa.Text(), nullable=True),
    sa.Column('final_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('final_thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('playlist_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('suggested_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('watch_time_minutes', sa.Float(), nullable=False),
    sa.Column('average_view_duration_seconds', sa.Float(), nullable=False),
    sa.Column('average_view_percentage', sa.Float(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('impressions_ctr', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics_snapshots')
    op.drop_table('videos')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
